# Generated by Django 5.2.7 on 2025-10-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('tele_contac', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('cod_repuesto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('pcio_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('cod_tipo_vehiculo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('empleado', 'Empleado')], default='empleado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('nro_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('vehiculo', models.CharField(max_length=12)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('mano_obra', models.FloatField(blank=True, null=True)),
                ('total_general', models.FloatField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.ForeignKey(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to='taller.persona')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.ForeignKey(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to='taller.persona'),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('nro_presupuesto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('total_presupuesto', models.FloatField(blank=True, null=True)),
                ('total_gastado', models.FloatField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
            ],
        ),
    ]
